default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
  url: <%= ENV['DATABASE_URL'] %>
  pool: 5

development:
  <<: *default
  database: rails-react-app_development

test:
  <<: *default
  database: rails-react-app_test

production:
  <<: *default
  database: rails-react_app_production