default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default

test:
  <<: *default
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  database: <%= ENV['DATABASE_NAME'] || 'mobilyweb_test' %>
  username: <%= ENV['DATABASE_USERNAME'] || 'postgres' %>  
  password: <%= ENV['DATABASE_PASSWORD'] || 'postgres' %>